
export const currencies = [
    { short: "ARS", long: "Argentine Peso" },
    { short: "AUD", long: "Australian Dollar" },
    { short: "BCH", long: "Bitcoin Cash" },
    { short: "BGN", long: "Bulgarian Lev" },
    { short: "BNB", long: "Binance Coin" },
    { short: "BRL", long: "Brazilian Real" },
    { short: "BTC", long: "Bitcoin" },
    { short: "CAD", long: "Canadian Dollar" },
    { short: "CHF", long: "Swiss Franc" },
    { short: "CNY", long: "Chinese Yuan" },
    { short: "CZK", long: "Czech Republic Koruna" },
    { short: "DKK", long: "Danish Krone" },
    { short: "DOGE", long: "Dogecoin" },
    { short: "DZD", long: "Algerian Dinar" },
    { short: "ETH", long: "Ethereum" },
    { short: "EUR", long: "Euro" },
    { short: "GBP", long: "British Pound Sterling" },
    { short: "HKD", long: "Hong Kong Dollar" },
    { short: "HRK", long: "Croatian Kuna" },
    { short: "HUF", long: "Hungarian Forint" },
    { short: "IDR", long: "Indonesian Rupiah" },
    { short: "ILS", long: "Israeli New Sheqel" },
    { short: "INR", long: "Indian Rupee" },
    { short: "ISK", long: "Icelandic Króna" },
    { short: "JPY", long: "Japanese Yen" },
    { short: "KRW", long: "South Korean Won" },
    { short: "LTC", long: "Litecoin" },
    { short: "MAD", long: "Moroccan Dirham" },
    { short: "MXN", long: "Mexican Peso" },
    { short: "MYR", long: "Malaysian Ringgit" },
    { short: "NOK", long: "Norwegian Krone" },
    { short: "NZD", long: "New Zealand Dollar" },
    { short: "PHP", long: "Philippine Peso" },
    { short: "PLN", long: "Polish Zloty" },
    { short: "RON", long: "Romanian Leu" },
    { short: "RUB", long: "Russian Ruble" },
    { short: "SEK", long: "Swedish Krona" },
    { short: "SGD", long: "Singapore Dollar" },
    { short: "THB", long: "Thai Baht" },
    { short: "TRY", long: "Turkish Lira" },
    { short: "TWD", long: "New Taiwan Dollar" },
    { short: "XRP", long: "Ripple" },
    { short: "ZAR", long: "South African Rand" },
]